language: node_js
node_js:
  - node
cache:
  npm: true

jobs:
  include:
    - stage: test-react-app
      install:
        - npm install
      script:
        - echo "Run react-app testing"
        - npm run build

    - stage: deploy-to-gh-pages
      install:
        - npm install
      cache:
        directories:
          - 'build'
      script:
        - npm run build
      deploy:
        skip_cleanup: true
        provider: pages
        github_token: $GITHUB_TOKEN
        target_branch: master
        local_dir: './build'
        on:
          all_branches: true

    - stage: test-deploy
      script: curl https://hkurobomaster.github.io
